FIX: indentation error on workflow file

diff --git a/.github/workflows/notify-e2e-after-dev-deploy.yml b/.github/workflows/notify-e2e-after-dev-deploy.yml
--- a/.github/workflows/notify-e2e-after-dev-deploy.yml
+++ b/.github/workflows/notify-e2e-after-dev-deploy.yml
@@ -18,16 +18,16 @@ jobs:
     - name: Trigger QA workflow
       env:
         GH_TOKEN: ${{ secrets.QA_DISPATCH_TOKEN }}
-        run: |
-          if [ -z "$GH_TOKEN" ]; then
-            echo "::error::The QA_DISPATCH_TOKEN secret is not configured"
-            exit 1
-          fi
+      run: |
+        if [ -z "$GH_TOKEN" ]; then
+          echo "::error::The QA_DISPATCH_TOKEN secret is not configured"
+          exit 1
+        fi
 
-          curl --fail-with-body --request POST \
-            --url https://api.github.com/repos/BrauUu/habit-tracker-qa/actions/workflows/328240552/dispatches \
-            --header "Accept: application/vnd.github+json" \
-            --header "Authorization: Bearer $GH_TOKEN" \
-            --header "Content-Type: application/json" \
-            --header "X-GitHub-Api-Version: 2026-03-10" \
-            --data "{\"ref\":\"main\",\"inputs\":{\"component\":\"backend\"}}"
+        curl --fail-with-body --request POST \
+          --url https://api.github.com/repos/BrauUu/habit-tracker-qa/actions/workflows/328240552/dispatches \
+          --header "Accept: application/vnd.github+json" \
+          --header "Authorization: Bearer $GH_TOKEN" \
+          --header "Content-Type: application/json" \
+          --header "X-GitHub-Api-Version: 2026-03-10" \
+          --data "{\"ref\":\"main\",\"inputs\":{\"component\":\"backend\"}}"
